package crypto

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"errors"
	"math/big"
)

// ValidatePublicKey checks if the given base64 string is a valid P-256 public key (either SPKI or 65-byte raw uncompressed format)
func ValidatePublicKey(publicKeyBase64 string) bool {
	if publicKeyBase64 == "" {
		return false
	}

	pubKeyBytes, err := base64.StdEncoding.DecodeString(publicKeyBase64)
	if err != nil {
		return false
	}

	// 1. Try parsing as SPKI/PKIX
	if parsedKey, err := x509.ParsePKIXPublicKey(pubKeyBytes); err == nil {
		if ecdsaKey, ok := parsedKey.(*ecdsa.PublicKey); ok {
			return ecdsaKey.Curve == elliptic.P256()
		}
	}

	// 2. Try parsing as raw P-256
	if len(pubKeyBytes) == 65 && pubKeyBytes[0] == 0x04 {
		x := new(big.Int).SetBytes(pubKeyBytes[1:33])
		y := new(big.Int).SetBytes(pubKeyBytes[33:65])
		return elliptic.P256().IsOnCurve(x, y)
	}

	return false
}

// VerifySignature verifies a digital signature generated by WebCrypto API (P-256, SHA-256, raw signature)
// message: raw data to verify (ciphertext + iv + timestamp)
// signatureBase64: base64-encoded signature (64-byte raw r||s format from WebCrypto)
// publicKeyBase64: base64-encoded public key (can be either 65-byte raw uncompressed format OR standard SPKI/PKIX format)
func VerifySignature(message []byte, signatureBase64 string, publicKeyBase64 string) (bool, error) {
	if signatureBase64 == "" || publicKeyBase64 == "" {
		return false, errors.New("signature or public key cannot be empty")
	}

	// 1. Decode public key from Base64
	pubKeyBytes, err := base64.StdEncoding.DecodeString(publicKeyBase64)
	if err != nil {
		return false, err
	}

	var pubKey *ecdsa.PublicKey

	// Try parsing as SPKI/PKIX first (standard API contract format)
	if parsedKey, err := x509.ParsePKIXPublicKey(pubKeyBytes); err == nil {
		if ecdsaKey, ok := parsedKey.(*ecdsa.PublicKey); ok {
			pubKey = ecdsaKey
		}
	}

	// Fallback to raw uncompressed 65-byte format if SPKI parsing failed
	if pubKey == nil {
		if len(pubKeyBytes) == 65 && pubKeyBytes[0] == 0x04 {
			x := new(big.Int).SetBytes(pubKeyBytes[1:33])
			y := new(big.Int).SetBytes(pubKeyBytes[33:65])
			pubKey = &ecdsa.PublicKey{
				Curve: elliptic.P256(),
				X:     x,
				Y:     y,
			}
		} else {
			return false, errors.New("invalid public key format, expected SPKI or 65-byte uncompressed raw key")
		}
	}

	// 2. Decode signature from Base64
	sigBytes, err := base64.StdEncoding.DecodeString(signatureBase64)
	if err != nil {
		return false, err
	}

	// WebCrypto ECDSA signature is raw r || s, which is 64 bytes for P-256
	if len(sigBytes) != 64 {
		return false, errors.New("invalid signature format, expected 64-byte raw signature")
	}

	r := new(big.Int).SetBytes(sigBytes[:32])
	s := new(big.Int).SetBytes(sigBytes[32:])

	// 3. Hash the message with SHA-256
	hash := sha256.Sum256(message)

	// 4. Verify using ecdsa standard library
	return ecdsa.Verify(pubKey, hash[:], r, s), nil
}
