package crypto

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"math/big"
)

// VerifySignature verifies a digital signature generated by WebCrypto API (P-256, SHA-256, raw signature)
// message: raw data to verify (ciphertext + iv + timestamp)
// signatureBase64: base64-encoded signature (64-byte raw r||s format from WebCrypto)
// publicKeyBase64: base64-encoded public key (65-byte raw uncompressed format from WebCrypto: 0x04 + 32-byte X + 32-byte Y)
func VerifySignature(message []byte, signatureBase64 string, publicKeyBase64 string) (bool, error) {
	if signatureBase64 == "" || publicKeyBase64 == "" {
		return false, errors.New("signature or public key cannot be empty")
	}

	// 1. Decode public key from Base64
	pubKeyBytes, err := base64.StdEncoding.DecodeString(publicKeyBase64)
	if err != nil {
		return false, err
	}

	// WebCrypto raw export for P-256 must be exactly 65 bytes
	// (0x04 uncompressed prefix + 32-byte X + 32-byte Y)
	if len(pubKeyBytes) != 65 || pubKeyBytes[0] != 0x04 {
		return false, errors.New("invalid public key format, expected 65-byte uncompressed P-256 raw key")
	}

	// Parse coordinates
	x := new(big.Int).SetBytes(pubKeyBytes[1:33])
	y := new(big.Int).SetBytes(pubKeyBytes[33:65])

	pubKey := &ecdsa.PublicKey{
		Curve: elliptic.P256(),
		X:     x,
		Y:     y,
	}

	// 2. Decode signature from Base64
	sigBytes, err := base64.StdEncoding.DecodeString(signatureBase64)
	if err != nil {
		return false, err
	}

	// WebCrypto ECDSA signature is raw r || s, which is 64 bytes for P-256
	if len(sigBytes) != 64 {
		return false, errors.New("invalid signature format, expected 64-byte raw signature")
	}

	r := new(big.Int).SetBytes(sigBytes[:32])
	s := new(big.Int).SetBytes(sigBytes[32:])

	// 3. Hash the message with SHA-256
	hash := sha256.Sum256(message)

	// 4. Verify using ecdsa standard library
	return ecdsa.Verify(pubKey, hash[:], r, s), nil
}
